### PR TITLE
fixes#148

### PR DESCRIPTION
**Pull request by davoustp**
Simplified Makefile, integration tests around the k8s auth engine accessor.

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
please see #150 , that is the way to fix this issue. Thank you very much for finding it.

**Comment by trevorbox** [comment]
@davoustp is it safe to remove the accessor exports in the README? for example https://github.com/redhat-cop/vault-config-operator#configure-an-kubernetes-authentication-mount-point

**Comment by davoustp** [comment]
> please see #150 , that is the way to fix this issue. Thank you very much for finding it.

@raffaelespazzoli not sure that this relates to this PR, but thanks nonetheless ;-)

**Comment by trevorbox** [comment]
> > @davoustp is it safe to remove the accessor exports in the README? for example https://github.com/redhat-cop/vault-config-operator#configure-an-kubernetes-authentication-mount-point
> 
> Blimey! thought I had this cleared as well. Yes, it should be safe. What's the best course, another PR probably?

That's fine then we can update it later if not now.

**Pull request merged**
